meta_product_name: "StudyCards"
meta_title: "StudyCards - Revolutionize the way you learn!"
meta_description: "You can create or choose the perfect flashcards for your studies. No worries we got your back!"
meta_image: "cover.png" # should exist in `app/assets/images/`
